export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR"
export const LOGOUT_USER = "LOGOUT_USER"

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'

export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CREATE_DEVICE_BEGIN = "CREATE_DEVICE_BEGIN"
export const CREATE_DEVICE_SUCCESS = "CREATE_DEVICE_SUCCESS"
export const CREATE_DEVICE_ERROR = "CREATE_DEVICE_ERROR"

export const GET_DEVICES_BEGIN = "GET_DEVICES_BEGIN"
export const GET_DEVICES_SUCCESS = "GET_DEVICES_SUCCESS"

export const SET_EDIT_DEVICE = "SET_EDIT_DEVICE"

export const DELETE_DEVICE_BEGIN = "DELETE_DEVICE_BEGIN"

export const EDIT_DEVICE_BEGIN = "EDIT_DEVICE_BEGIN"
export const EDIT_DEVICE_SUCCESS = "EDIT_DEVICE_SUCCESS"
export const EDIT_DEVICE_ERROR = "EDIT_DEVICE_ERROR"

export const SHOW_STATS_BEGIN = "SHOW_STATS_BEGIN"
export const SHOW_STATS_SUCCESS = "SHOW_STATS_SUCCESS"

export const CLEAR_FILTERS = "CLEAR_FILTERS"

export const CHANGE_PAGE = "CHANGE_PAGE"
