export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SHOW_MODAL = 'SHOW_MODAL'

export const CHANGE_ISMEMBER_STATE = 'CHANGE_ISMEMBER_STATE'

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR"
export const TOGGLE_MAP_SIDEBAR = "TOGGLE_MAP_SIDEBAR"
export const LOGOUT_USER = "LOGOUT_USER"

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'

export const CLEAR_VALUES = 'CLEAR_VALUES'
export const CLEAR_VALUES_DEVICE_DATA = 'CLEAR_VALUES_DEVICE_DATA'

export const CREATE_DEVICE_DATA_BEGIN = "CREATE_DEVICE_DATA_BEGIN"
export const CREATE_DEVICE_DATA_SUCCESS = "CREATE_DEVICE_DATA_SUCCESS"
export const CREATE_DEVICE_DATA_ERROR = "CREATE_DEVICE_DATA_ERROR"

export const CREATE_DEVICE_BEGIN = "CREATE_DEVICE_BEGIN"
export const CREATE_DEVICE_SUCCESS = "CREATE_DEVICE_SUCCESS"
export const CREATE_DEVICE_ERROR = "CREATE_DEVICE_ERROR"

export const GET_DEVICES_BEGIN = "GET_DEVICES_BEGIN"
export const GET_DEVICES_SUCCESS = "GET_DEVICES_SUCCESS"

export const GET_DEVICE_DATA_BEGIN = "GET_DEVICES_DATA_BEGIN"
export const GET_DEVICE_DATA_SUCCESS = "GET_DEVICES_DATA_SUCCESS"
export const GET_ALL_DEVICE_DATA_SUCCESS = "GET_ALL_DEVICE_DATA_SUCCESS"

export const GET_ALL_USERS_DEVICES_SUCCESS = "GET_ALL_USERS_DEVICES_SUCCESS"

export const SET_EDIT_DEVICE = "SET_EDIT_DEVICE"
export const SET_DETAILS_DEVICE = "SET_DETAILS_DEVICE"

export const DELETE_DEVICE_BEGIN = "DELETE_DEVICE_BEGIN"
export const DELETE_DEVICE_DATA_BEGIN = "DELETE_DEVICE_DATA_BEGIN"

export const EDIT_DEVICE_BEGIN = "EDIT_DEVICE_BEGIN"
export const EDIT_DEVICE_SUCCESS = "EDIT_DEVICE_SUCCESS"
export const EDIT_DEVICE_ERROR = "EDIT_DEVICE_ERROR"

export const SHOW_STATS_BEGIN = "SHOW_STATS_BEGIN"
export const SHOW_STATS_SUCCESS = "SHOW_STATS_SUCCESS"

export const CLEAR_FILTERS = "CLEAR_FILTERS"

export const CHANGE_PAGE = "CHANGE_PAGE"
export const SET_PAGE_NUMBER = "SET_PAGE_NUMBER"
export const SET_SORT_OPTION = "SET_SORT_OPTION"

export const CREATE_SUBSCRIPTION_BEGIN = "CREATE_SUBSCRIPTION_BEGIN"
export const CREATE_SUBSCRIPTION_SUCCESS = "CREATE_SUBSCRIPTION_SUCCESS"
export const CREATE_SUBSCRIPTION_ERROR = "CREATE_SUBSCRIPTION_ERROR"

export const GET_SUBSCRIPTIONS_BEGIN = "GET_SUBSCRIPTIONS_BEGIN"
export const GET_ALL_SUBSCRIPTIONS_SUCCESS = "GET_ALL_SUBSCRIPTIONS_SUCCESS"
export const DELETE_SUBSCRIPTION_BEGIN = "DELETE_SUBSCRIPTION_BEGIN"